### ISSUE TITLE
Split into subpackages?

### ISSUE THREAD

**Issue by devmotion** [SciML/DiffEqProblemLibrary.jl#87]
Would it be possible to move the submodules into separate packages, possibly in this repo? I still manage to hit pre-compilation/module loading issues with the current setup (a while ago: https://github.com/SciML/DiffEqProblemLibrary.jl/issues/51), and the current setup with `importodeproblems()` etc. that cause evaluation into the submodules is arguably a bit ugly. Personally I think it would be much nicer to be able to just write `using DDEProblemLibrary` instead of
```julia
using DiffEqProblemLibrary.DDEProblemLibrary
DDEProblemLibrary.importddeproblems()
```

**Comment by ChrisRackauckas** [comment]
Yes, this should be made into subpackages.
